# Incidence Matrixes

In [1]:
sample_bbc_news_sentences = [
    "China confirms Interpol chief detained",
    "Turkish officials believe the Washington Post writer was killed in the Saudi consulate in Istanbul.",
    "US wedding limousine crash kills 20",
    "Bulgarian journalist killed in park",
    "Kanye West deletes social media profiles",
    "Brazilians vote in polarised election",
    "Bull kills woman at French festival",
    "Indonesia to wrap up tsunami search",
    "Tina Turner reveals wedding night ordeal",
    "Victory for Trump in Supreme Court battle",
    "Clashes at German far-right rock concert",
    "The Walking Dead actor dies aged 76",
    "Jogger in Netherlands finds lion cub",
    "Monkey takes the wheel of Indian bus"
]

In [2]:
#basic tokenization
from nltk.tokenize import TweetTokenizer

tokenizer = TweetTokenizer()
sample_bbc_news_sentences_tokenized = [tokenizer.tokenize(sent) for sent in sample_bbc_news_sentences]
sample_bbc_news_sentences_tokenized[0]

['China', 'confirms', 'Interpol', 'chief', 'detained']

In [3]:
sample_bbc_news_sentences_tokenized_lower = [[_t.lower() for _t in _s] for _s in sample_bbc_news_sentences_tokenized]
sample_bbc_news_sentences_tokenized_lower[0]

['china', 'confirms', 'interpol', 'chief', 'detained']

In [4]:
#get all unique tokens
unique_tokens = set(sum(sample_bbc_news_sentences_tokenized_lower, []))
unique_tokens

{'.',
 '20',
 '76',
 'actor',
 'aged',
 'at',
 'battle',
 'believe',
 'brazilians',
 'bulgarian',
 'bull',
 'bus',
 'chief',
 'china',
 'clashes',
 'concert',
 'confirms',
 'consulate',
 'court',
 'crash',
 'cub',
 'dead',
 'deletes',
 'detained',
 'dies',
 'election',
 'far-right',
 'festival',
 'finds',
 'for',
 'french',
 'german',
 'in',
 'indian',
 'indonesia',
 'interpol',
 'istanbul',
 'jogger',
 'journalist',
 'kanye',
 'killed',
 'kills',
 'limousine',
 'lion',
 'media',
 'monkey',
 'netherlands',
 'night',
 'of',
 'officials',
 'ordeal',
 'park',
 'polarised',
 'post',
 'profiles',
 'reveals',
 'rock',
 'saudi',
 'search',
 'social',
 'supreme',
 'takes',
 'the',
 'tina',
 'to',
 'trump',
 'tsunami',
 'turkish',
 'turner',
 'up',
 'us',
 'victory',
 'vote',
 'walking',
 'was',
 'washington',
 'wedding',
 'west',
 'wheel',
 'woman',
 'wrap',
 'writer'}

In [5]:
# create incidence matrix (term-document frequency)
import numpy as np
incidence_matrix = np.array([[sent.count(token) for sent in sample_bbc_news_sentences_tokenized_lower] 
                    for token in unique_tokens])
print(incidence_matrix)

[[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]


For a bigger vocab can take too much memory (number of tokens * number of documents), while also being sparse!

Which words will have highest and which lowest Total freq?

# Dataset 
https://archive.ics.uci.edu/ml/datasets/Twenty+Newsgroups 

In [6]:
!ls data/mini_newsgroups/sci.electronics/
!tail -50 data/mini_newsgroups/sci.electronics/52464 | head -10

52464  53511  53655  53741  53820  53891  53971  54092	54157  54265
52758  53521  53664  53742  53824  53892  53976  54096	54160  54302
52766  53529  53669  53750  53829  53909  53986  54111	54165  54305
52792  53569  53675  53769  53837  53911  54010  54114	54175  54306
52794  53574  53676  53772  53839  53913  54041  54115	54176  54310
52817  53584  53683  53777  53850  53915  54042  54122	54212  54325
52820  53589  53692  53804  53865  53918  54057  54132	54224  54337
52822  53640  53706  53808  53868  53921  54066  54140	54244  54353
52830  53641  53708  53812  53871  53935  54069  54143	54248  54489
53508  53653  53712  53818  53872  53938  54090  54147	54255  54490
Lines: 48

In article <1993Mar25.161909.8110@wuecl.wustl.edu> dp@cec1.wustl.edu (David Prutchi) writes:
>In article <C4CntG.Jv4@spk.hp.com> long@spk.hp.com (Jerry Long) writes:
>>Fred W. Culpepper (fculpepp@norfolk.vak12ed.edu) wrote:
>>[...]
>>A couple of years ago I put together a Tesla circuit which
>>was published 

# You will now have to construct the Inverted Index - only the dictionary part (term and #docs)

In [7]:
import nltk
nltk.download('punkt')


[nltk_data] Downloading package punkt to /home/tony/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [8]:
from nltk.tokenize import sent_tokenize
from collections import defaultdict, Counter
import os
    
def prepare_dataset(documents_dir):
    tokenized_documents = []
    for document in os.listdir(documents_dir):
        with open(os.path.join(documents_dir, document)) as outf:
            sentence_tokens = [tokenizer.tokenize(sent.lower()) for sent in sent_tokenize(outf.read())]
            tokenized_documents.append(np.array(sum(sentence_tokens, [])))
    print("Found documents: ", len(tokenized_documents))
    return tokenized_documents      
    
def document_frequency(tokenized_documents):
    all_unique_tokens = set(sum(tokenized_documents, []))
    print("Found unique tokens: ", len(all_unique_tokens))
    
    tokens = {token: sum([1 for doc in tokenized_documents if token in doc]) 
                    for token in all_unique_tokens}
    return tokens

In [9]:
# Load data
selected_category = 'data/mini_newsgroups/sci.crypt/'
print(selected_category)
tokenized_dataset = prepare_dataset(selected_category)
print("Sample tokenized document:")
print(tokenized_dataset[0])

data/mini_newsgroups/sci.crypt/
Found documents:  100
Sample tokenized document:
['xref' ':' 'cantaloupe.srv.cs.cmu.edu' 'sci.chem' ':' '12409' 'sci.misc'
 ':8' '170' 'sci.chem.organomet' ':' '70' 'sci.cryonics' ':' '1040'
 'sci.crypt' ':' '16088' 'sci.engr.chem' ':' '1346' 'newsgroups' ':'
 'sci.chem' ',' 'sci.misc' ',' 'sci.chem.organomet' ',' 'sci.cryonics' ','
 'sci.crypt' ',' 'sci.engr.chem' 'path' ':' 'cantaloupe.srv.cs.cmu.edu'
 '!' 'magnesium.club.cc.cmu.edu' '!' 'news.sei.cmu.edu' '!'
 'cis.ohio-state.edu' '!' 'zaphod.mps.ohio-state.edu' '!' 'sdd.hp.com' '!'
 'hplabs' '!' 'nsc' '!' 'gatekeeper.nsc.com' '!' 'voder' '!' 'jamesl'
 'from' ':' 'jamesl@galaxy.nsc.com' '(' 'james' 'lu' 'x3702' ')' 'subject'
 ':' 'how' 'to' 'make' 'this' 'illuminating' 'thing' '?' 'message-id' ':'
 '<c65vtk.11m@voder.nsc.com>' 'sender' ':' 'news@voder.nsc.com'
 'nntp-posting-host' ':' 'gallium.nsc.com' 'organization' ':' 'national'
 'semiconductor' ',' 'santa' 'clara' 'distribution' ':' 'usa' 'date' '

In [10]:
# statistics

all_terms = np.concatenate(tokenized_dataset).ravel()
unique_terms = np.unique(all_terms)
unique_terms.sort()

document_count = len(tokenized_dataset)
all_terms_count = len(all_terms)
unique_terms_count = len(unique_terms)

print("documents count: {}".format(document_count))
print("total term count: {}".format(all_terms_count))
print("unique term count: {}".format(unique_terms_count))

documents count: 100
total term count: 42440
unique term count: 5801


In [11]:
# incidence matrix
# rows are documents
# columns are terms
incidence_matrix = np.zeros([document_count, unique_terms_count])

# construct postings array of tuples
# each tuple is of the form: (term_id, doc_id, frequency of term in doc, positions of term in doc)
# the tuple can be expanded even more
postings = []

for term_id, term in enumerate(unique_terms):
    for doc_id, doc in enumerate(tokenized_dataset):
        positions_of_term_in_doc = np.where(doc == term)[0]
        term_count_in_doc = positions_of_term_in_doc.size
        
        if term_count_in_doc > 0:
            postings.append((term_id, doc_id, term_count_in_doc, positions_of_term_in_doc))
        
        incidence_matrix[doc_id, term_id] = term_count_in_doc

In [12]:
# construct lexicon
# key: term
# value: [total term frequency, document frequency of term]

lexicon = {term: [
               incidence_matrix[:, term_id].sum(), # total term frequency
               np.count_nonzero(incidence_matrix[:, term_id]) # document frequency of term
           ]
           for term_id, term in enumerate(unique_terms)}

In [13]:
postings

[(0, 0, 10, array([37, 39, 41, 43, 45, 47, 49, 51, 53, 55])),
 (0, 1, 6, array([ 18,  20,  22,  24,  26, 110])),
 (0, 2, 7, array([ 3,  5,  7,  9, 11, 13, 15])),
 (0, 3, 8, array([ 6,  8, 10, 12, 14, 16, 18, 20])),
 (0, 4, 11, array([17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37])),
 (0, 5, 5, array([21, 23, 25, 27, 29])),
 (0, 6, 7, array([ 6,  8, 10, 12, 14, 16, 18])),
 (0, 7, 7, array([ 3,  5,  7,  9, 11, 13, 15])),
 (0, 8, 9, array([18, 20, 22, 24, 26, 28, 30, 32, 34])),
 (0,
  9,
  20,
  array([ 24,  26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,
          50,  52,  54, 260, 262, 264, 266])),
 (0,
  10,
  12,
  array([  6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26, 112])),
 (0, 11, 7, array([ 3,  5,  7,  9, 11, 13, 15])),
 (0, 12, 8, array([ 6,  8, 10, 12, 14, 16, 18, 20])),
 (0, 13, 8, array([ 3,  5,  7,  9, 11, 13, 15, 17])),
 (0, 14, 5, array([12, 14, 16, 18, 20])),
 (0, 15, 11, array([ 24,  26,  28,  30,  32,  34,  36,  38,  40, 138, 140])),
 (0, 16, 11, array(

# What's next in research:

- <a href='http://nbjl.nankai.edu.cn/Lab_Papers/2018/SIGIR2018.pdf'>Index Compression for BitFunnel Query Processing</a>
- <a href='https://link.springer.com/chapter/10.1007/978-3-319-76941-7_47'>Inverted List Caching for Topical Index Shards</a>
